# Generated by Django 4.0.5 on 2022-06-14 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('Modification_time', models.DateTimeField(auto_now=True)),
                ('Description', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('O', 'open'), ('IN', 'inprogress'), ('F', 'finished')], default='O', max_length=2)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
        ),
    ]
