# Generated by Django 4.0.4 on 2022-06-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('Modification_time', models.DateTimeField(auto_now=True)),
                ('Description', models.TextField(max_length=30)),
                ('developer', models.CharField(max_length=30)),
                ('created_by', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('O', 'open'), ('IN', 'inprogress'), ('F', 'finished')], default='O', max_length=2)),
            ],
        ),
    ]
