# Generated by Django 4.0.5 on 2022-06-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applied_developer',
            field=models.ManyToManyField(null=True, to='accounts.developer'),
        ),
    ]
