# Generated by Django 4.0.4 on 2022-06-10 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Job',
        ),
    ]
