# Generated by Django 4.0.4 on 2022-06-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_person_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Description',
            field=models.TextField(max_length=255),
        ),
    ]
