# Generated by Django 4.0.4 on 2022-06-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
