# Generated by Django 4.0.4 on 2022-06-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_job_first_name_remove_job_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='name',
        ),
        migrations.AddField(
            model_name='job',
            name='job_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
