# Generated by Django 4.0.5 on 2022-06-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_developer_can_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='cv',
            field=models.FileField(null=True, upload_to='static/cv'),
        ),
    ]
