# Generated by Django 4.0.5 on 2022-06-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_developer_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('DEVELOPER', 'Developer'), ('COMPANY', 'Company')], max_length=50, verbose_name='type'),
        ),
    ]
