# Generated by Django 4.0.5 on 2022-06-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('jobs', '0001_initial'),
        ('accounts', '0005_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_apply',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cv',
            field=models.FileField(null=True, upload_to='static/cv'),
        ),
        migrations.AddField(
            model_name='user',
            name='history',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.ManyToManyField(to='jobs.job'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_by_mail',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(to='tags.tag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('DEVELOPER', 'Developer'), ('COMPANY', 'Company')], max_length=10, verbose_name='type'),
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
    ]
