# Generated by Django 4.0.5 on 2022-06-11 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_developer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_apply',
        ),
        migrations.RemoveField(
            model_name='user',
            name='history',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notify_by_mail',
        ),
        migrations.AddField(
            model_name='developer',
            name='can_apply',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='notify_by_mail',
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.CharField(max_length=500, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
